"""Build-generated sources are held aside, and the near-miss is not. [1.26]

The cost case is easy: a Hybris estate's `bootstrap/gensrc` holds one `*Model` class per
item type — thousands of files, none of them a decision anybody made — and the target's
own build regenerates the equivalent anyway. Skipping them is most of the difference
between a cheap run and an expensive one.

The *risk* case is what these tests are really about. Hybris generates an abstract half
and a developer-editable half of the same pair, so a rule keyed on `extends Generated*`
or on a `*Model.java` filename would delete exactly the hand-written half — silently,
and with no failing test anywhere. The reference corpus contains a real example
(`AcmecoreConstants extends GeneratedAcmecoreConstants`, holding six business config
keys), which is why it appears here as a fixture in its own right.
"""

import textwrap

import pytest

from src.agentic.blackboard import Blackboard
from src.ingest import _is_generated_source, ingest

BANNER = textwrap.dedent("""\
    /*
     * ----------------------------------------------------------------
     * --- WARNING: THIS FILE IS GENERATED AND WILL BE OVERWRITTEN! ---
     * ----------------------------------------------------------------
     */
    package com.acme.core.model;

    public class OrderModel extends GeneratedOrderModel {
        public String getCode() { return code; }
    }
    """)

# The near-miss: generated *name*, hand-written *content*. Six real config keys.
NEAR_MISS = textwrap.dedent("""\
    package com.acme.core.constants;

    /**
     * Global class for all Acmecore constants. Generated by the Hybris extension template.
     */
    public final class AcmecoreConstants extends GeneratedAcmecoreConstants {
        public static final String DISCOUNT_THRESHOLD_KEY = "acmecore.pricing.discount.threshold";
        public static final String GOLD_RATE_KEY = "acmecore.loyalty.gold.rate";
    }
    """)

ORDINARY = textwrap.dedent("""\
    package com.acme.core.service;

    public class DefaultOrderService {
        public void placeOrder(String code) { }
    }
    """)


@pytest.mark.parametrize("path,source,expect", [
    # Machine-written evidence — a build-owned directory or the generator's own banner.
    ("/p/bootstrap/gensrc/com/acme/model/OrderModel.java", "package a;", True),
    ("/p/target/generated-sources/com/acme/Stub.java", "package a;", True),
    ("/p/src/com/acme/model/OrderModel.java", BANNER, True),
    ("/p/src/com/acme/Foo.java", "// @generated by wsdl2java\npackage a;", True),

    # Not evidence. Each of these would cost real business logic if it skipped.
    ("/p/src/com/acme/constants/AcmecoreConstants.java", NEAR_MISS, False),
    ("/p/src/com/acme/service/DefaultOrderService.java", ORDINARY, False),
    ("/p/src/com/acme/model/OrderModel.java", "package a;\npublic class OrderModel {}", False),
    ("/p/src/com/acme/GeneratedReportBuilder.java", "package a;", False),
])
def test_only_machine_written_evidence_counts(path, source, expect):
    assert bool(_is_generated_source(path, source)) is expect


def test_a_banner_deep_in_a_string_literal_is_not_a_declaration():
    """The file's own header declares it generated. A quote of that phrase does not."""
    src = "package a;\n" + ("// filler\n" * 400) + '\nString s = "THIS FILE IS GENERATED";\n'
    assert _is_generated_source("/p/src/com/acme/Doc.java", src) == ""


def _tree(root):
    gen = root / "bootstrap" / "gensrc" / "com" / "acme" / "core" / "model"
    gen.mkdir(parents=True)
    (gen / "OrderModel.java").write_text(BANNER, encoding="utf-8")

    src = root / "src" / "com" / "acme" / "core"
    (src / "constants").mkdir(parents=True)
    (src / "constants" / "AcmecoreConstants.java").write_text(NEAR_MISS, encoding="utf-8")
    (src / "service").mkdir(parents=True)
    (src / "service" / "DefaultOrderService.java").write_text(ORDINARY, encoding="utf-8")
    return root


def test_ingest_holds_generated_aside_and_keeps_the_near_miss(tmp_path):
    res = ingest(str(_tree(tmp_path)))

    held = {g["class_name"] for g in res["generated"]}
    kept = {c["class_name"] for c in res["classes"]}

    assert held == {"OrderModel"}, "only the build-generated file should be held aside"
    assert "AcmecoreConstants" in kept, "the hand-written half of the pair must survive"
    assert "DefaultOrderService" in kept
    assert res["generated"][0]["reason"], "a skip with no reason is a silent drop"


def test_a_held_aside_file_still_gets_a_ledger_row(tmp_path):
    """Held aside is not the same as unaccounted for.

    The ledger's claim is that every source file has a row. A file that leaves no row is
    indistinguishable from one the migration lost, so the saving is only defensible if
    the skip is visible.
    """
    res = ingest(str(_tree(tmp_path)))
    bb = Blackboard(str(tmp_path), str(tmp_path / "out"))
    bb.generated = res["generated"]

    row = next(r for r in bb.completeness_ledger() if r["source"] == "OrderModel")
    assert row["outcome"] == "skipped"
    assert "build-generated" in row["note"]
    assert "regenerates" in row["note"], "the note must say why skipping is safe"
